name: CRC Pull Request Flow
on:
  pull_request:
    branches:
      - main
    ##Pull request with changes to crc-code directory only
    paths:
      - 'crc-code/**'
      - '!crc-iac-azure/**'
      - '!crc-iac-azure-test/**'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  create-test-infra:
    runs-on: ubuntu-latest
    outputs:
      rg_name: ${{ steps.rg_name.outputs.RGNAME }}
      app_name: ${{ steps.app_name.outputs.APP_NAME }}
      api_endpoint: ${{ steps.api_endpoint.outputs.API_ENDPOINT }}
    steps:
        
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_CRC }}
          ##Directory with terraform infrastructure
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: true 

        ##Intialise, format code and deploy terraform infra
      - name: Deploying Terraform Infrastructure
        run: |
              cd ./crc-iac-azure-test 
              terraform init -upgrade
              terraform fmt
              terraform apply -auto-approve
              terraform refresh
              echo "RGNAME=$(terraform output rgname)" >> $GITHUB_OUTPUT
              echo $RGNAME
              echo "APP_NAME=$(terraform output appname)" >> $GITHUB_OUTPUT
              echo $APP_NAME
              echo "API_ENDPOINT=$(terraform output api-endpoint)" >> $GITHUB_OUTPUT
              echo $APP_NAME

        ##Delete Infrastructure on failure
      - name: Delete terraform infra on failure
        run: |
             cd ./crc-iac-azure-test
             terraform destroy -auto-approve
        if: ${{ failure() }}
        


  deploy-azure-api-merge-request:
    needs: create-test-infra
    runs-on: ubuntu-latest

    ##If env does not work here, move it to just before the azure command
   
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_CRC }}
      
        #Directory with code to be tested
      - name: changing directory to crc-code
        run: cd crc-code
      - name: installing zip and zipping function
        run: |
              apt-get install zip -y
              zip -rv crc_code_test.zip .  
      - name: deploy zipped file to azure
        uses: azure/CLI@v1
        env:
          RG_NAME: ${{ needs.create-test-infra.outputs.rg_name }}
          APP_NAME: ${{ needs.create-test-infra.outputs.app_name }}
        with:
          inlineScript: |
            az webapp deployment source config-zip --resource-group ${{ env.RG_NAME }} --name ${{ env.APP_NAME }} --src crc_code_test.zip
      - name: Deleting infrastructure on failure
        uses: azure/CLI@v1
        env:
          RG_NAME: ${{ needs.create-test-infra.outputs.rg_name }}
        with:
          inlineScript: |
            echo ${{ env.RG_NAME }}
            az group delete -n ${{ env.RG_NAME }} -y
        if: ${{ failure() }}
  
  cypress-api-endpoint-test:
    needs: deploy-azure-api-merge-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_CRC }}

      - name: Changing directory to cypress test directory
        run: cd cypress-test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/apitest.cy.js
        env:
          CYPRESS_API_ENDPOINT: ${{ needs.create-test-infra.outputs.api_endpoint }}
      - name: Deleting infrastructure on failure
        uses: azure/CLI@v1
        env:
          RG_NAME: ${{ needs.create-test-infra.outputs.rg_name }}
        with:
          inlineScript: |
            az group delete --name ${{ env.RG_NAME }} -y
        if: ${{ failure() }}

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: cypress-api-endpoint-test
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_CRC }}
      - name: changing directory to crc-code
        run: cd crc-code
      - name: installing zip and zipping function
        run: |
              apt-install zip -y
              zip -rv crc_code_test.zip .

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-pers-prod-01'
          slot-name: 'production'
          package: './crc_code_test.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
        
      - uses: azure/CLI@v1
        env:
          RG_NAME: ${{ needs.create-test-infra.outputs.rg_name }}
        with:
          inlineScript: |
            az group delete --name ${{ env.RG_NAME }} -y
        if: ${{ always() }}
        
    
        
          
            
              

      


        

            


